image:
  tag: "v5.17.14"

ingress:
  enabled: true
  className: "nginx"
  host: storefront.yas.local.com
  annotations: {}
  hosts:
    - host: storefront.dev.yas.local.com
      paths:
        - path: /swagger-ui
          pathType: ImplementationSpecific
  tls: []

urls: "[{ url: '/api/product/v3/api-docs', name: 'Product' },
      { url: '/api/media/v3/api-docs', name: 'Media' },
      { url: '/api/customer/v3/api-docs', name: 'Customer' }, 
      { url: '/api/cart/v3/api-docs', name: 'Cart'},
      { url: '/api/rating/v3/api-docs', name: 'Rating' }, 
      { url: '/api/order/v3/api-docs', name: 'Order'},
      { url: '/api/payment/v3/api-docs', name: 'Payment'},
      { url: '/api/location/v3/api-docs', name: 'Location'}, 
      { url: '/api/inventory/v3/api-docs', name: 'Inventory'},
      { url: '/api/tax/v3/api-docs', name: 'Tax' },
      { url: '/api/promotion/v3/api-docs', name: 'Promotion'},
      { url: '/api/search/v3/api-docs', name: 'Search'}]"